apiVersion: v1
kind: Namespace
metadata:
  name: concourse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: concourse-db
  name: concourse-db 
  namespace: concourse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-db
  template:
    metadata:
      labels:
        app: concourse-db
    spec:
      containers:
      - name: postgres
        image: postgres:14.2
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: concourse-db
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: concourse-db
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-db
              key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: concourse-db
  name: concourse-db
  namespace: concourse
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: concourse-db
  type: NodePort
