---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-db-password
  namespace: databases
spec:
  encryptedData:
    password: AgBuv/uQ4yOJx8R8Ic+o9OdvrK+LltlQxGxf245sN1toVSi3xUhOkQxFkL/J6KxnIIhLtUd2XKACT/xMZZq7peoDN5PF9xIlqpeUFike6pQae3RNt55QtkEyTMrESdY3T70IH6ChA05xUM5UN0lmvfsuRnRaQnbfdiHmlhFe+kZ0OaesL01w8zXzulB1t8OP2sQNxbgfNYDTj6m59HLJgAPIP3gIsUOrdsBO30lmgT3K+kGpptlX8vTe9WHCPdT2VrVJv7IZy5xOuuixrUupvQifvEmP1Ks0pNwCj09Rhoe+YFLVxPLgH3q9QiOPSuxZO3NXZ0J95aS32WlX2Ai/etv0OhBQGkeKslgju3fMKHL47VlXDo52o6wrT6g2cOtmi6g4lykjH3yX72XjDGanSeNeMRFJrTn/oW+cEz0zcr5J2TvGpazTMnbMzqx5flH2mV7q45238jaAm7rbFbW71+37M5kR56Sm3tozDGGeg6uzPz8w8JoXy0+/B5NGg1kR/yiUV1T3z8Gsz9oHyZKI+To2Zf9ZqcETOtz2o0iKcBRBIo6c7ba7vB26MdiVwzUqn0VyDGDk9JZuEMa8PouI0ITIbYQMza+Ga54Mpdo87/KylrtiSRB3ebBlnNBklZCFuEWk2Mu0Z7PQGMu49hA0pFRQxx4QW+AZ+fiCkRkXhLb+gdKV6B9z9ef01oIBL6KsThkuwabLFn9WjsCoPkMA2AagOyPVdOEgarVi0MIbYGPhpy67pTv3KocIOIffSV1RuFf+yg==
    username: AgAJyTt7bC+2SDbjcmc7dXOjQhPJi/ipPe7vG4lfWwv3k5XBUbh42KJBpS7Kn5lZJOKvp+8sRRE5kBm/eGT9SYQXaar2cwENWbgt39VaartLP9xpx6PByELq4lrOQ90ckPyOYqRjNrMeArZ4QT9M8jYU/IsaphQ0nlgwC8ZFOhN5WkEG68AMNaieeCoyJ+JfQxjL2KsYVARWxZkyKazGuHydOzMrWVcXBItH/J8ikd/5muUgyUVnnid0iQfvdAl82L4QjAb31oMQ0/4Il9/RLWc+p40sAGF0f6jK8W4AymBYiLH7T2vZURqFfn4gjESyc3hv98TAc3IHeLv/1I3EZqK725BGW2Y+6VxHbVpac5PW+MqEZ+FfASUsur6d5db+rIdJy/mRsN7QYp4uI3Pe8WSv77FWxD69UMhoGJ2gVkoXCp1Jk8/xmO6InhmRl7J5oP+lcOHdgvUU7uTi4vmjJSjw79B9u8s0g7igUgzzPz6pu/wSW29+jvSgGSgZoR4lOKeSKMa41suad90rEwHlm6ufB+RdnfTESNkPD10BKDNwdSrLZJ9EbwC07G+GlhLvYteT+3ItTkW/pmG8zSRxHGgfRRViaGToqOVrnoFzhBPeA+BlVOauh8xgwwdnhUx+3KzLr3qcJJtt+0jQJ9y/6Xh8USyWc15FKs3IjdcO5ATGswKsBWcVtOjlDG78s32VkK25BnbkQofjd+M+Wojn
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: homeassistant-db-password
      namespace: databases
    type: kubernetes.io/basic-auth
