---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-db-password
  namespace: databases
spec:
  encryptedData:
    password: AgBQ001amO150ldtaFRIwxj/OtO8Iy8oKB06is8Hjxq6cTYAQ+ZGhs9g+EWMBj/2222h0ADaQK2VNQwHcz2lZjq2OZVfMa3aIYAIyZ8AGYgAdYp6mPOT2Xc4cbu0IRZNROf3zVw8R9IR4J6uyT4B5RFGSfFGsXYI6wp3pNcjhbkzZgatQpX+Ay906+ZOcyZjVvwlWbhtgUXIAauRP5TR5sEyfaBmYtEYRTm79XbA4tbtAVVbYctDVD2KRebISl/SB5TWnbiM6tSnic4DIr1g7EwxmHcPxI/z926McSG0hh2YtIB3SEL8a8I517cyx4HLWTKlVfwWFalRj54yMmg9AAeWLsL+Nv57TMrWnFZA5elaGvKHQZ8P5XJpkLHCKCE5FvqeGf+gwpKXpMy01dH/WkhAgAwVTH0qnCe4E3H/CnFzrhrQsLm5VsoRUQxCR4+xTUtwAgiybzZBN4fc5KueiwPZoS/1eJ1KLI5sRrBFdj2n13/0jnxsrCit/fe3rcpM2IBfFOuZQ3pXje75G9CISkJXH4o0GLmNPnLFxezlFwbxZuucYJnOTDC8IbgH2u6f/WGTKEzmH2LBZkyuvwv4nHFVas556CoiPjaPC79BNx9FTtN1JnkI2uID0qJLDHzCoZV4679VlgMx4rHhD9XMHMhMBQpBXx3ApkRwO1vYZytgsXTZklvUOA6PHrhyjGcbskOSCsjIejh20Lj9biZcQswRqMAr+Y7YEpjaf6pkQYXaBGNQ2py4bntEe3GnT/is3LNhgg==
    username: AgAAO9JNJpWyEkKLxsnrvv442VKh6qkJN63HNk3KdBIzoH+10R5KUcTTEtIxG9lcgbxa5X/Ksb465QzKOXZ6ZQ/P3ccpNCwcdy1v+PbEHz2KY5Z5J6yRqolkaIz9p6HoO31NH57g4T423KDuPcDLyW0sOT+DVYvQSdj/RNqgYkX35W5oxEwm2a9y1mlPGnN9M07jIdxijESiBX59k3WQcqHRIYZqfN0kZrmWNtLM5TDKZWtcFMqNl5x6r7cLU4eaIAcFvxT88g6ZBW1USDb18m44YYeM0/loeiIy6aCaSeGmo9Ud3pKHHNYdyqDB1qCWxlfOoNPSqLfG5i062kIFvHflfvlMbXIACko+ln2tM3i4JZLGk4sX3BRwkRyCnzAf3OWmwRWpxQzyqDmzqV7UtdPiUE8ToY6lS6HhsrX0l/5+bSm2uzb6FCVaYQm58zRBA0crtwkBWhnIlKNDU9jTkZ99c1S8MHqbsBS4Ghs7VnddsSkfU5tLM06kIeX4RXvLjAAKkfOWc5R7bWmGtnFVQo/Nrbbcmpr5H7qAHkBuiUD4bMO9nhS/qjQt/hEIfnRZ1E5NOnC6X4ayKQpNQT3eWaKCwY76xXI72Vyd4lAqbQWnPdyNpFk10r37+rlD9pZuCwyk2pMVWyHt3m5fy5ng1Q6QtFA+Od9b6jnffAbqqrNuGxekOkiXujfO9efzEDWllNPSlCWAITb1qlxsh92o
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: homeassistant-db-password
      namespace: databases
    type: kubernetes.io/basic-auth
