---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudnative-pg-helm-release.yaml
  - cluster.yaml
  - databases.yaml
  - mealie-db-password.yaml
  - homeassistant-db-password.yaml
  - backup-pvc.yaml
  - backup-cronjob.yaml
