---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-db-password
  namespace: databases
spec:
  encryptedData:
    password: AgCUjz8R7zsHK90KlU5lwiWY7057sK/pxvWkO4TsLgaV7TlEprT2cA8yK/6+d2cVKRxQoYQx1tSJevADCCCC4pJ8AqMjZy092zrNqbtESnw6rP/w4o4YlMv0aJd1h+5fOC63uATL6H3wWmTOyVMUwxDWgGYgDf3bDoKjavjkMC6IkYdqIr8ZHStIgEUtvAyX662UHF9qK1PAI+d3morqBc7B4eTfsRpXoaKmhSyDGLsJN8sef2UHtalz6s216kTUz0GdRHGqdWVc1QaiEFZYtDASlMY7FsfONuQJOe5+/6b0x5hvYoYz1JHHzAJA+Tt0e0IZYnZNS/azVqQU2AUYD/DAUO6igCkI0TZQHpzk4SwlvmnX8j8VcTx47FMKGF+si3vzdnroWg56BiktMa3esLZ5y26KOq3kXhMtRnGloOLUOrHqtq7PTGsET2g+rawg/XneG5/6aJcfZiPsd5YLdESh5NZ/zMI7p/ZHQ4p0bl5rUJMHWuiwjRJ7pumMmoSk8bvsGAvxUgqYCJx+DwWn2RYZUrtmyvJ4RY9shDZCdmXiOxjRjdkLRoeTDBoo9l54NZa3flWPjMYP/rsdKTNfsN+f3fpFA9CGRXAB2u5PNme/f91Ze1dO3kpB3BfWmS7liYu/5+g5GM9OQZoxI5XeDodKW42/vgoLTckyQZzE/BieR1dNBweMTGmK8ua7BSD9tVj10i4+z07Xib1okBRrJ6eX9BiDYcibxLWY68u+m/negxooSYgm9g2DGl2VWclKbgMz7w==
    username: AgAZZIJWU95dihMbmPoZvt9d44H+jIyBp39131+078fJeEN3B0ulV48i/ZFL4KykQI4hdxudTzqucsLPcwxsiuapmvPXgIxwoNk4Fqr8/utBlnrtJgpmNS8m7bCEeGoP3zAAWx1JKBJf5LO6UEnIWI/ZOnz9Qjk35NToXwD0EJr+G2a69VtNQHq1jXbBth2t1GYyQ2XVIwZJKKe6RK2XGZ1h+r+2ADWo1QtmtZM8g8u2+dX85GpUztfedKWLhePfm8BCmBbk3qLRv4DfxYVlv4pMcssvW4wecb+olO3sXRbd+CYJaqG8Pyc1Atxav50PhLA+WahL/Mm/KjVO1tOmbjFNrY+COwLBK6sny0xJjnR0to66NEG6vu+gF2fcBTzCTboD18Rh3BsixT34cVp4JfD6YgFyb2W5OJTAc/UHcjlL7WQHC+/MjF7BH16oM3NbmvGRazJTCHO/BKYce81V25HeqANiDqDHnxlzCqiYGjafOIoJIOXcqeTTZBGVfOSr5A1ScIEy6n3jO8ZaguMRBC5j0z2evM1lLhLQbhljv70np2NkV+fGdwz+RGDbLewTa4r5SpqH6ndDrTWTtKe6tt3+5O0hYxpz4KDMKWdTnbPPoFuGf2dl6bLHPkrftw+RFky06RrcyN7XqQfbGfPwxM2QQowXl1IMSeaPUUPng4Zhh7In7ZvLniHerTqNPfLcCWUbgNppiTY=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: mealie-db-password
      namespace: databases
    type: kubernetes.io/basic-auth
