---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost:5.2.3
        name: ghost
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: https://petewall.net
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
  - protocol: TCP
    port: 2368
    targetPort: 2368
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  namespace: ghost
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: public
  rules:
  - host: petewall.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ghost
            port:
              number: 2368
  tls:
  - hosts:
    - petewall.net
    secretName: ghost-tls
