---
apiVersion: v1
kind: Namespace
metadata:
  name: ghost
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghost
  namespace: ghost
automountServiceAccountToken: true
---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
- path: [metadata, annotations, volume.kubernetes.io/selected-node]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: PersistentVolumeClaim
      name: ghost-storage
      namespace: ghost
- path: [metadata, annotations, volume.kubernetes.io/storage-provisioner]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: PersistentVolumeClaim
      name: ghost-storage
      namespace: ghost
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-storage
  namespace: ghost
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      serviceAccountName: ghost
      securityContext:
        fsGroup: 1001
      containers:
      - image: ghost:5.5
        name: ghost
        env:
        - name: url
          value: https://petewall.net
        ports:
        - name: http
          containerPort: 2368
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: "http"
        #     scheme: HTTP
        #   initialDelaySeconds: 120
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 6
        #   successThreshold: 1
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: "http"
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 6
        #   successThreshold: 1
        volumeMounts:
        - name: ghost-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-storage
        persistentVolumeClaim:
          claimName: ghost-storage
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
  - protocol: TCP
    port: 2368
    targetPort: 2368
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  namespace: ghost
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: public
  rules:
  - host: petewall.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ghost
            port:
              number: 2368
  tls:
  - hosts:
    - petewall.net
    secretName: ghost-tls
