#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  namespace: concourse-main
data:
  username: #@ base64.encode(data.values.dockerhub.username.strip())
  password: #@ base64.encode(data.values.dockerhub.password.strip())
---
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: concourse-main
data:
  access_token: #@ base64.encode(data.values.github.access_token.strip())
  private_key: #@ base64.encode(data.values.github.private_key.strip())
---
apiVersion: v1
kind: Secret
metadata:
  name: wifi
  namespace: concourse-main
data:
  ssid: #@ base64.encode(data.values.wifi.ssid.strip())
  password: #@ base64.encode(data.values.wifi.password.strip())
