#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  namespace: concourse-main
data:
  username: #@ base64.encode(data.values.dockerhub.username)
  password: #@ base64.encode(data.values.dockerhub.password)
---
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: concourse-main
data:
  access_token: #@ base64.encode(data.values.github.access_token)
  private_key: #@ base64.encode(data.values.github.private_key)
---
apiVersion: v1
kind: Secret
metadata:
  name: wifi
  namespace: concourse-main
data:
  ssid: #@ base64.encode(data.values.wifi.ssid)
  password: #@ base64.encode(data.values.wifi.password)
---
apiVersion: v1
kind: Secret
metadata:
  name: nasa
  namespace: concourse-main
data:
  apikey: #@ base64.encode(data.values.nasa.apikey)
