---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: concourse-db-user-password
  namespace: concourse
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      POSTGRES_PASSWORD: $(value)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: concourse-db-configuration
  namespace: concourse
data:
  PGDATA: /data/pgdata
  POSTGRES_DB: concourse
  POSTGRES_USER: concourse
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: concourse-db 
  namespace: concourse
  labels:
    app: concourse-db
spec:
  serviceName: "concourse-db"
  replicas: 1
  selector:
    matchLabels:
      app: concourse-db
  template:
    metadata:
      labels:
        app: concourse-db
    spec:
      containers:
      - name: postgres
        image: postgres:14.4
        envFrom:
        - configMapRef:
            name: concourse-db-configuration
        - secretRef:
            name: concourse-db-user-password
        volumeMounts:
        - mountPath: /data
          name: concourse-db-storage
  volumeClaimTemplates:
  - metadata:
      name: concourse-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: concourse-db
  namespace: concourse
  labels:
    app: concourse-db
spec:
  type: ClusterIP
  selector:
    app: concourse-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
