#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata": {"name": "concourse-web-prometheus"}}), expects="1+"
---
metadata:
  annotations:
    #@overlay/remove
    prometheus.io/port: "9391"
    #@overlay/remove
    prometheus.io/scrape: "true"
    #@overlay/match missing_ok=True
    k8s.grafana.com/scrape: "true"
    #@overlay/match missing_ok=True
    k8s.grafana.com/job: "integrations/concourse"
    #@overlay/match missing_ok=True
    k8s.grafana.com/port: "9391"
