apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  namespace: concourse
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: concourse-web
  namespace: concourse
subsets:
  - addresses:
      - ip: 192.168.2.10
    ports:
      - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concourse-web
  namespace: concourse
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: ci.petewall.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: concourse-web
            port:
              number: 8080
