#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SSHKey
metadata:
  name: worker-key
  namespace: concourse
spec: {}
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SSHKey
metadata:
  name: tsa-host-key
  namespace: concourse
spec: {}
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: session-signing-key
  namespace: concourse
spec: {}
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: concourse-web
  namespace: concourse
spec:
  inputResources:
  - name: session-signing-key
    ref:
      apiVersion: v1
      kind: Secret
      name: session-signing-key
      namespace: concourse
  - name: tsa-host-key
    ref:
      apiVersion: v1
      kind: Secret
      name: tsa-host-key
      namespace: concourse
  - name: worker-key
    ref:
      apiVersion: v1
      kind: Secret
      name: worker-key
      namespace: concourse
  template:
    data:
      host-key: $(.tsa-host-key.data.ssh-privatekey)
      session-signing-key: $(.session-signing-key.data.key\.pem)
      worker-key-pub: $(.worker-key.data.ssh-authorizedkey)
      local-users: #@ base64.encode(data.values.username + ":" + data.values.password)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: concourse-worker
  namespace: concourse
spec:
  inputResources:
  - name: tsa-host-key
    ref:
      apiVersion: v1
      kind: Secret
      name: tsa-host-key
      namespace: concourse
  - name: worker-key
    ref:
      apiVersion: v1
      kind: Secret
      name: worker-key
      namespace: concourse
  template:
    data:
      host-key-pub: $(.tsa-host-key.data.ssh-authorizedkey)
      worker-key: $(.worker-key.data.ssh-privatekey)
