#@ load("@ytt:data", "data")
---
concourse:
  web:
    auth:
      mainTeam:
        localUser: #@ data.values.username
    externalUrl: https://ci.petewall.net
    kubernetes:
      createTeamNamespaces: false
    tracing:
      otlpAddress: k8s-monitoring-grafana-agent.monitoring.svc:4317
    prometheus:
      enabled: true
  worker:
    baggageclaim:
      #! Needed to prevent issues with: failed to create volume
      driver: btrfs
    tracing:
      otlpAddress: k8s-monitoring-grafana-agent.monitoring.svc:4317

web:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - ci.petewall.net
    ingressClassName: public
    tls:
    - hosts:
      - ci.petewall.net
      secretName: concourse-web-tls
  service:
    prometheus:
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/job: "integrations/concourse"
        k8s.grafana.com/port: "9391"

worker:
  enabled: true
  replicas: 2

persistence:
  worker:
    storageClass: synology-nfs

postgresql:
  enabled: true
  auth:
    database: concourse
    username: #@ data.values.pgusername
    password: #@ data.values.pgpassword
    postgresPassword: #@ data.values.pgpassword
  primary:
    persistence:
      storageClass: synology-nfs

secrets:
  create: false
