apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: chart
  contents:
  - path: .
    helmChart:
      name: concourse
      version: "17.0.14"
      repository:
        url: https://concourse-charts.storage.googleapis.com/