---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: concourse
  namespace: monitoring
  labels:
    instance: primary
spec:
  endpoints:
  - honorLabels: true
    interval: 60s
    metricRelabelings:
    - action: replace
      replacement: integrations/kubernetes/concourse-web
      targetLabel: job
    - action: keep
      regex: concourse_builds_aborted_total|concourse_builds_check_aborted_total|concourse_builds_check_errored_total|concourse_builds_check_failed_total|concourse_builds_check_finished_total|concourse_builds_check_running|concourse_builds_check_started_total|concourse_builds_check_succeeded_total|concourse_builds_duration_seconds|concourse_builds_errored_total|concourse_builds_failed_total|concourse_builds_finished|concourse_builds_finished_total|concourse_builds_running|concourse_builds_started_total|concourse_builds_succeeded_total|concourse_caches_get_step_cache_hits|concourse_caches_streamed_resource_caches|concourse_db_connections|concourse_db_queries_total|concourse_gc_created_containers_to_be_garbage_collected|concourse_gc_created_volumes_to_be_garbage_collected|concourse_gc_creating_containers_to_be_garbage_collected|concourse_gc_destroying_containers_to_be_garbage_collected|concourse_gc_destroying_volumes_to_be_garbage_collected|concourse_gc_failed_containers_to_be_garbage_collected|concourse_gc_failed_volumes_to_be_garbage_collected|concourse_gc_gc_artifact_collector_duration|concourse_gc_gc_build_collector_duration|concourse_gc_gc_container_collector_duration|concourse_gc_gc_resource_cache_collector_duration|concourse_gc_gc_resource_cache_use_collector_duration|concourse_gc_gc_resource_config_check_session_collector_duration|concourse_gc_gc_resource_config_collector_duration|concourse_gc_gc_task_cache_collector_duration|concourse_gc_gc_volume_collector_duration|concourse_gc_gc_worker_collector_duration|concourse_http_responses_duration_seconds|concourse_jobs_scheduled_total|concourse_jobs_scheduling|concourse_jobs_schedulingDuration|concourse_lidar_checks_enqueued_total|concourse_lidar_checks_finished_total|concourse_lidar_checks_started_total|concourse_locks_held|concourse_steps_wait_duration|concourse_volumes_orphaned_volumes_to_be_deleted|concourse_volumes_volumes_streamed|concourse_workers_containers|concourse_workers_registered|concourse_workers_tasks|concourse_workers_unknown_containers|concourse_workers_unknown_volumes|concourse_workers_volumes
      sourceLabels:
      - __name__
    path: /metrics
    port: prometheus
  namespaceSelector:
    matchNames:
    - concourse
  selector:
    matchLabels:
      app: concourse-web
