testFramework:
  enabled: false
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - lab.petewall.net
  tls:
  - hosts:
    - lab.petewall.net
    secretName: grafana-tls
admin:
  existingSecret: grafana-admin
# datasources:
#   datasources.yaml:
#     apiVersion: 1
#     datasources:
#     - name: InfluxDB
#       type: influxdb
#       access: proxy
#       url: http://influxdb.monitoring.svc.cluster.local
