---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
- path: [metadata, annotations, volume.kubernetes.io/selected-node]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: PersistentVolumeClaim
      name: agent-eventhandler
      namespace: monitoring
- path: [metadata, annotations, volume.kubernetes.io/storage-provisioner]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: PersistentVolumeClaim
      name: agent-eventhandler
      namespace: monitoring
