---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  name: kube-state-metrics
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  name: kube-state-metrics
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  name: kube-state-metrics
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  name: kube-state-metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/version: 2.5.0
    spec:
      automountServiceAccountToken: true
      containers:
      - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.5.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 65534
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kube-state-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: ksm-monitor
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 60s
    metricRelabelings:
    - action: keep
      regex: kubelet_certificate_manager_server_ttl_seconds|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_node_name|storage_operation_errors_total|kubelet_volume_stats_inodes_used|kube_statefulset_status_replicas_ready|kube_statefulset_replicas|container_fs_reads_bytes_total|kubelet_cgroup_manager_duration_seconds_count|kube_daemonset_status_current_number_scheduled|kube_node_spec_taint|kubelet_runtime_operations_errors_total|kube_deployment_status_observed_generation|kube_statefulset_status_current_revision|kubelet_certificate_manager_client_ttl_seconds|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_pod_container_resource_limits|container_fs_writes_bytes_total|go_goroutines|kubelet_running_pod_count|kube_daemonset_status_desired_number_scheduled|kubelet_running_pods|kube_node_info|kubelet_server_expiration_renew_errors|container_network_transmit_bytes_total|container_cpu_cfs_throttled_periods_total|kubelet_pod_start_duration_seconds_count|process_cpu_seconds_total|node_namespace_pod_container:container_memory_rss|kube_pod_container_status_waiting_reason|container_network_receive_packets_dropped_total|container_fs_writes_total|kubelet_node_config_error|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_pleg_relist_duration_seconds_bucket|namespace_workload_pod|kube_job_status_active|kube_daemonset_status_number_misscheduled|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kube_horizontalpodautoscaler_spec_min_replicas|kube_deployment_status_replicas_available|kubelet_volume_stats_inodes|kube_statefulset_status_observed_generation|kube_node_status_condition|namespace_memory:kube_pod_container_resource_limits:sum|machine_memory_bytes|kubernetes_build_info|container_network_receive_packets_total|volume_manager_total_volumes|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|kube_statefulset_status_update_revision|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|container_network_receive_bytes_total|container_memory_cache|kube_job_status_start_time|container_network_transmit_packets_total|kubelet_pod_worker_duration_seconds_count|kube_job_failed|kube_node_status_allocatable|node_namespace_pod_container:container_memory_cache|namespace_cpu:kube_pod_container_resource_requests:sum|kube_daemonset_status_number_available|kube_pod_container_resource_requests|kube_resourcequota|kube_horizontalpodautoscaler_status_desired_replicas|container_cpu_cfs_periods_total|namespace_cpu:kube_pod_container_resource_limits:sum|kubelet_pleg_relist_interval_seconds_bucket|kube_horizontalpodautoscaler_status_current_replicas|kube_statefulset_metadata_generation|container_cpu_usage_seconds_total|kube_pod_info|storage_operation_duration_seconds_count|container_memory_swap|kube_deployment_status_replicas_updated|kubelet_running_container_count|process_resident_memory_bytes|kubelet_volume_stats_capacity_bytes|kube_statefulset_status_replicas_updated|container_memory_working_set_bytes|kubelet_running_containers|kube_deployment_metadata_generation|kubelet_pleg_relist_duration_seconds_count|kubelet_volume_stats_available_bytes|rest_client_requests_total|kube_pod_owner|container_fs_reads_total|kubelet_pod_start_duration_seconds_bucket|kube_deployment_spec_replicas|namespace_memory:kube_pod_container_resource_requests:sum|kube_horizontalpodautoscaler_spec_max_replicas|node_namespace_pod_container:container_memory_swap|kube_node_status_capacity|container_network_transmit_packets_dropped_total|kubelet_pod_worker_duration_seconds_bucket|kube_replicaset_owner|kubelet_runtime_operations_total|kube_statefulset_status_replicas|node_namespace_pod_container:container_memory_working_set_bytes|kube_namespace_status_phase|container_memory_rss|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|kube_daemonset_status_updated_number_scheduled|namespace_workload_pod:kube_pod_owner:relabel|kube_pod_status_phase|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node.*|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum
      sourceLabels:
      - __name__
    path: /metrics
    port: http-metrics
    relabelings:
    - action: replace
      replacement: integrations/kubernetes/kube-state-metrics
      targetLabel: job
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
