#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
data:
  admin-user: #@ base64.encode(data.values.grafana.username)
  admin-password: #@ base64.encode(data.values.grafana.password)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: influxdb-admin
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      INFLUXDB_USER: admin
      INFLUXDB_TOKEN: $(value)  #! Required because telegraph needs an environment variable without a dash
      admin-password: $(value)  #! Required because InfluxDB specifically looks for this key 
      admin-token: $(value)     #! Required because InfluxDB specifically looks for this key
