#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: logs-secret
  namespace: monitoring
type: Opaque
stringData:
  password: #@ data.values.logs.password
  username: #@ data.values.logs.username
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-secret
  namespace: monitoring
type: Opaque
stringData:
  username: #@ data.values.metrics.username
  password: #@ data.values.metrics.password
