#@ load("@ytt:data", "data")
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: storage-snmp-monitor
  namespace: monitoring
spec:
  name: snmp
  type:
    unique: true
  config:
    snmp_targets:
    - name: storage
      address: 192.168.1.123
    walk_params:
      private:
        version: 3
        auth:
          username: #@ data.values.storage_snmp.username
          password: #@ data.values.storage_snmp.password
          auth_protocol: #@ data.values.storage_snmp.protocol
          priv_password: #@ data.values.storage_snmp.priv_password
          priv_protocol: #@ data.values.storage_snmp.priv_protocol
