#@ load("@ytt:data", "data")
---
cluster:
  name: wallhouse

externalServices:
  prometheus:
    host: #@ data.values.metrics.host
    basicAuth:
      username: #@ data.values.metrics.username
      password: #@ data.values.metrics.password

  loki:
    host: #@ data.values.logs.host
    basicAuth:
      password: #@ data.values.logs.password
      username: #@ data.values.logs.username

  tempo:
    host: #@ data.values.traces.host
    basicAuth:
      password: #@ data.values.traces.password
      username: #@ data.values.traces.username

metrics:
  alloy:
    metricsTuning:
      useIntegrationAllowList: true

  kube-state-metrics:
    extraMetricRelabelingRules: |
      rule {
        source_labels = ["__name__", "provider_id", "node"]
        separator = "@"
        regex = "kube_node_info@@(.*)"
        replacement = "microk8s://${1}"
        action = "replace"
        target_label = "provider_id"
      }

  node-exporter:
    metricsTuning:
      useIntegrationAllowList: true

  cost: {enabled: false}
  probes: {enabled: false}
  podMonitors: {enabled: false}
  serviceMonitors: {enabled: false}
  kepler:
    enabled: true

logs:
  pod_logs:
    extraRelabelingRules: |-
      rule {
        source_labels = ["__meta_kubernetes_pod_node_name"]
        target_label = "node"
        action = "replace"
      }
  journal:
    enabled: true

traces:
  enabled: true

configAnalysis:
  enabled: false

configValidator:
  enabled: false

test:
  enabled: false

opencost:
  enabled: false

prometheus-operator-crds:
  enabled: false

kepler:
  enabled: true

alloy-logs:
  alloy:
    mounts:
      extra:
        - name: storage
          mountPath: /tmp/alloy
  controller:
    volumes:
      extra:
        - name: storage
          hostPath:
            path: /var/alloy-log-storage
            type: DirectoryOrCreate
