apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: kubernetes-monitoring
    # helmChart:
    #   name: kubernetes-monitoring
    #   repository:
    #     url: https://github.com/grafana/kubernetes-monitoring-chart
    git:
      url: https://github.com/grafana/kubernetes-monitoring-chart
      ref: origin/main
    includePaths:
      - charts/kubernetes-monitoring/**