---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-db-password
  namespace: mealie
spec:
  encryptedData:
    password: AgCXyvSijqr8X8xTNKdVnzrMuNbkpflOtP58CjGT+HjsDKXJahXs99ypNrNg8cRMyt/IA77tV30KgtutHrttyXZbonHWH9BWwle+wYH/gb7Y8mEAcINZF0+DoVCkA19EteW6a9RtbYWqlolsAic08hD3g0rNdSBg+/Okmgn7EDGjofAZQm1o3nRQa5tfN+gRxs0JhvhMuUFdouBYz4iV7K3JRIGhcaP1RTsYgGoEXZ6Y+d4vXDOFfnOSVvxC8JBf49IqHmH/ZlVE556oljHBcmV/NlpBY4zL2fU+RLLv6LFSDmpDApGEwN8VGo2rF+e8yASQBEpKxvxRjB/oy7aD8rUwnCl2nSeyZWSGgcWZGsbD4Yxt6MMmRvbaLeccuCF16uYc8iY3k1AshEY4jsSE5dGOjWBw1TiRKU8XK+jteOBSXFKn4lnT+yh4aMYxOSCG9HghQZcFwRIYnP7uST4GKVz20eR6/RKXRzhsE4e3tbekRVdE7SCttdtbinW9zFY7vR3NkJ+9TdW0FpXQbhokFb2YZbRdzIfnzyEo2NoZrxtP9eIuu3E5ylC9skCDWJybiO2g+jxidIKtqbRwQ+UBUUY0COyXrzvd3G//Vt80ntVhh0Z4iCNJKaqbHWsIeR5pRqD6EX2SUvZxR3TEL/YcuoD42bwY2SN6UKyr/hZS+UQYc2w+LaWwI18KqNRHiu6A8o9IvEnNRirTzbNhlpX06Eit7CEx7iuOq7AMY7FuzDVEeIT0OohEW20/9ZLO+1afUMSuaw==
  template:
    metadata:
      name: mealie-db-password
      namespace: mealie
