---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: istio-system
spec:
  interval: 1h
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 1h
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
  valuesFrom:
    - kind: Secret
      name: kiali-grafana-cloud
      valuesKey: prometheusUrl
      targetPath: external_services.prometheus.url
    - kind: Secret
      name: kiali-grafana-cloud
      valuesKey: prometheusUser
      targetPath: external_services.prometheus.auth.username
  values:
    auth:
      strategy: anonymous
    external_services:
      grafana:
        enabled: false
      prometheus:
        auth:
          type: basic
          password: secret:kiali-grafana-cloud:prometheusPassword
