---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-logger
  namespace: career
data:
  PORT: "8081"
  FILE: /data/events.log
  DEBUG: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-logger
  namespace: career
spec:
  selector:
    matchLabels:
      app: event-logger
  serviceName: event-logger
  replicas: 1
  template:
    metadata:
      labels:
        app: event-logger
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: event-logger
        image: ghcr.io/petewall/event-logger
        envFrom:
        - configMapRef:
            name: event-logger
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: event-logger-data
          mountPath: /data
      - name: event-log
        image: ubuntu
        envFrom:
        - configMapRef:
            name: event-logger
        command:
        - bash
        - -c
        - |
          touch "${FILE}"
          cat "${FILE}"
          tail -f "${FILE}"
        volumeMounts:
        - name: event-logger-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: event-logger-data
    spec:
      storageClassName: synology-nfs
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: event-logger
  namespace: career
  labels:
    app: event-loggerexporter
  annotations:
    k8s.grafana.com/scrape: "true"
    k8s.grafana.com/job: "event-logger"
spec:
  selector:
    app: event-logger
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
