---
apiVersion: v1
kind: ConfigMap
metadata:
  name: okr-service
  namespace: career
data:
  PORT: "8080"
  DATASTORE_TYPE: fs
  DATASTORE_FORMAT: yaml
  DATASTORE_PATH: /data/okrs.yaml
  DEBUG: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: okr-service
  namespace: career
spec:
  selector:
    matchLabels:
      app: okr-service
  serviceName: okr-service
  replicas: 1
  template:
    metadata:
      labels:
        app: okr-service
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: okr-service
        image: ghcr.io/petewall/okr-service
        envFrom:
        - configMapRef:
            name: okr-service
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: okr-service-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: okr-service-data
    spec:
      storageClassName: synology-nfs
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: okr-service
  namespace: career
  labels:
    app: okr-serviceexporter
  annotations:
    k8s.grafana.com/scrape: "true"
    k8s.grafana.com/job: "okr-service"
spec:
  selector:
    app: okr-service
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
