---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: huggingface
  namespace: kubeai
spec:
  encryptedData:
    token: AgAKqpdH32yBAJs14HAc6u4nicvIjZQ5IzxYVDRhsicmKTJFiy27qmN0+Ghts8B3sES+4aniZhGMiJKWoa1O03bXvmqqOWaMvEfQCpL8pHv/92z3MYyk0dokPp2vjBBG8hxZXslEkHQhV4aB/qW+ZGLZ5VJS3bVPhunf4Snl4iteXyZd1jH49uGVinWO/LA2r2LV2xQqnez/+8L6/hx+PnJnT+NeDhFaAZdh1EHt+0McdqgK7bXgd+xsJnEkSzCFEtUvJyWDEMwcrDxtZj8+oRaEayteitY8PRianpEf+7Jv8l3Th1G3kLcxyiWIW86KrwxNUJfKpxSmwp1f7paik7wsCGM9tVOAbwB7afdZUR6cMRL4a8wB2oZi04ktjbDhgjarvn4R+eHH3wRmuEqwvLhQ5B1CTH6KRAfkPH3KRg7uuRZacNT2aVXFMZO7pcS6JWheCCEAblny5jOG8PmRiaNPXwzdUL3V0ZcISPz7hTin4YjULi1pvS4IloT4rEQoBYtbf1G/V+CpSbFSKHW3IxzIC4JJx6XgLnHGJ3zNfvRXk9ixB8PDJonrEI5urF+3luoL7yib4NPW2DaEWhkp2mhOaTOt5LkWVtgzZkFyfPoBaQ9CYgb+SaRMDukGXHNf0XohAmny1DID08IycfrHQGbE5gNxYGO2b14aw+AKpPSp332fsB7lFyLENZoOa+GC0Z9sF596lL68XJPHf8WCL8Z1pHyfOvXzBC6SW9MBFWOn4UNtc2IV
  template:
    metadata:
      name: huggingface
      namespace: kubeai
