---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCRuleSTFhVytvAoKCbkq/sgRsF5lNo6PKYIMG+hTpAIwWVBRWHjDGq8aSX8aUWxclOXZDoSspYOo19XlT95ue9TxztOoIJP1rMorZHSdMybYhnI2RSmP7yzNjrcppE9mZWFkg5fj7nqYitoWcpMoQwoi4jL/mITlz9DgemEMn01YMBtTf+myKZhk4DGjKeuldSVPd5ZnoioNNllPnpQNiNF0bKMVXTYFXabHuVuBwJjRr1I3Ts2ghcMgPi+ykgelwLWEif6Rzn1XAigkQfNCJUgFi/oC2jtsnE3HgYvnjKue0/XIhca0JUT9hwiaH8YpM3jE6pIH/2YNor/jTQ2Tmlq1d+/5e0KEMQFI254/szn0iuIG7yOFRsXM/4U/D0f9pJkCofY2v0zkp3hi3aK3Xnof2yHvP90/PdAiKnqpcb1/grqHhM2SzfkF6LHF06bs/yFTnoTiZEzNyBNZ7kpvk3P5qLeVHRPjqPgCvCAToiaap6zLXw77OO7QjTA0ysYGQwFoHZOSVbJ3q2Ec9muAAIMr20Vy0nbUj6qFaKRSEgFKdJFwwhmcjP6fDFyQ1yL+vwOfGf9dLkmXdN6W44bRDgYUX9r56zh6EvldmVZSeUjUuNr0RX6igmlc1JKrcj04B4CgWQ3Q+TAlxdeR6oUE10HGtuEILyL20ScLvtvjDiEzOEiotYjIBbfXamFsviAKzuVKq8nj02nc1lTj+VxGFvtn5vMvJmgr3mqjfP980vqr3t0HtLWmb9
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
