#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "ddclient-" + data.values.url
  namespace: network
data:
  username: #@ base64.encode(data.values.username.strip())
  password: #@ base64.encode(data.values.password.strip())
