#@ load("@ytt:data", "data")
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: #@ "dynamic-dns-" + data.values.domain
  namespace: network
spec:
  concurrencyPolicy: Replace
  schedule: "@hourly"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dynamic-dns
            image: nixery.dev/shell/curl/jq
            command:
            - sh
            - -c
            - #@ data.values.script
            env:
            - name: DOMAIN
              value: #@ data.values.domain
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: token
          restartPolicy: Never
