---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: network
spec:
  type: ExternalName
  externalName: homeassistant.localdomain
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: network
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: public
  rules:
  - host: home.petewall.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 8123
  tls:
  - hosts:
    - home.petewall.net
    secretName: homeassistant-tls
