---
apiVersion: batch/v1
kind: Job
metadata:
  name: dynamic-dns-petewall.net
  namespace: network
spec:
  template:
    spec:
      containers:
      - name: dynamic-dns
        image: curlimages/curl
        imagePullPolicy: IfNotPresent
        args:
        - -X
        - POST
        - -u
        - $(USERNAME):$(PASSWORD)
        - https://domains.google.com/nic/update?hostname=ci.petewall.net
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: ddclient-ci.petewall.net
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ddclient-ci.petewall.net
              key: password
      restartPolicy: OnFailure
