#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  namespace: network
data:
  token: #@ base64.encode(data.values.cloudflare.token.strip())
