---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: krr-github
  namespace: krr
spec:
  encryptedData:
    token: AgBhHqjmexN6/eeEou2NPdf0hLt+KfJ/u9Vnx5BHqlGZNwILPRwLVf6NsISo4cDFEYqVeboQsUKwFxHiHrraC9k+CRNqx6tkldMY1PuAQWm5HJHZdxHL6D5QO0zP1Jk8P6u7MIM+zV9byFUu6dWlMH9wihkdDmHUcgm4Jb1uNxpRym0cSup5NeZKFeaXRUGDDcku0T3pCAbF5SSmH1GN0f0pIlDM1WYivJWMWJ2zc3uAx8qaxBYQfn0Qb+dUktnR3PVPOMeQhPnhljds2XP0Kze7JiqX2UHlZp38lXHTcLGAEN8mXhrzUtbvX///Bmps+O7R8IAswAIreJiHwZEzFuba9isPrA+E8roQm/gGLL0OnSLs7n1TpTvfLTxf5AI13zP2EgFekgHUQK3EXnec9FjlHsVr2u2klKKBb/aDLWU38VKsttGha/3W1VZcfl9X40OpaiFxyju7WXBQaJKCKWafULpZOdWOkPPSnnxZYUyzAMFaKssdSWIibS/9kWnPN8y8zWqqZfxm2wjJ9hDXsyhVO7WOfLUmQaXb+FHah/3A3jEZjyK7I6qa+Y9yVRmt5I3BXiujXDX8rHPB142b5mywGckgWq0FOvRB53M64sffFFPf2DZBI++A8KbGWFXFVDFl1qfv5UQidofQP2JN3fJOPE5AaPbFLkPdj7J/xfClITFTUV/1ADVgo5/duvZxDDnMzkxaV59b7k7/ku7ptZ2BAUtLKzHnUfnpTHL36F1e2EplnomvlFYSkA/LvMbCawwGewrLjJnmuZ7M8PVoJvANU+LgUKGQSSCmAx3wcjzjdxy+cPtlcJar1iEk6oY=
  template:
    metadata:
      name: krr-github
      namespace: krr
