---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - cronjob.yaml
  - prometheus-secret.yaml
  # - github-secret.yaml  # uncomment after `make github-secret.yaml`
configMapGenerator:
  - name: krr-report-script
    files:
      - report.py
generatorOptions:
  disableNameSuffixHash: true
