---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-secrets
  namespace: homeassistant
spec:
  encryptedData:
    secrets.yaml: AgCW2lCumDVrPUk4EywS4s6ayqBMcMfuzXKbugYvskTTeDxgZW8WFvnyubHYsJMpDL21sZ0N+JYluanPcA4gYLc464J56iFIjHXbnYir0Bzh+4kaKQi8dw0Wzsk7PyU4jh8N+nIgphZDiDTlyq59RYS8NkC+nkf8tG98Pnk2jx0rE/8yU1NPYd+qiCmnTME5Rrd4nOSe7LuijwiA9D8KMaJl8Vlx3wYdskLAbJSWzeuaCSliBHTYavkAuLmpcmi7WGtfrmCwZNnGSLZXRUXCy8yQRPtNvrpzaDpM8YzRxke22tDpI48CCP/10WH+6CzAn0/zEBeMpP1O5UHPtEr0Mp0Z9dqFJO38u1SF4MF3u1uPhCWRQLSWcYkUQjs0nhMdIdGmeIYaF5WQpfG8+3KcA2DWmHXdeOJuwJ2ItFddhc31KeFcgRZxxM7r+7cOpwXNvufC6Eo3aFz12cFcJ3t9+G9dKK6KRC+ZMs4WbcxUttcqUu1+9a/GX61E3PFysDqe7WrS9CNDF7QS86w6H8WIHBEffbXNSo+029PWSfCG9S5czthZ+yh9UT9VoWYkFy2eaB7cRF0qo6MdtQro+IPa8IE7MHSna0Ulz0qTAkDb0/Cvkv0leWyN5vs4Hb9p6lZLWgvPK/YWZ8ZMaKxKiZKh13h9xTg9js+vTQA9xh31OsUXoAtBw8h3Lm8XM+pugyf/Rwak4dei7KUFEiAvfQmof/nXZqvLLjQVRqcFLOQ7mJnRpgfzyRHtV7rdSpXHJvhCXlURwYUZ+IcSEzgciW0qelWVrW8b8yf4AsIFK3D6sETO7pVCkfeoCkuc8UMJLA6kUONfu9CVHvXFrBVXiI0Zd746yHNcO9AdlobMagpAP7ktE7RMRL081g8sOGOEQTbiwxuvkBzsIB0QC6TcyB7GW45kenboM3/DDgE=
  template:
    metadata:
      name: homeassistant-secrets
      namespace: homeassistant
