---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-secrets
  namespace: homeassistant
spec:
  encryptedData:
    secrets.yaml: AgCcc2I6Fu6+nFOIbRRl+qFptKdx+VzlIy6PMXjrztrzXjSaHMAOjbH9bVK9Dp2pvMsWZiToYaN2tm9x+wDgCpMYysWd+M27R+TZcHnZkrwuL7KR+kpFaw8ci6JuzJdg4joLApV3A8SVu06JCwccDs5oty0DWi9Yq7nbpFyjgT1MQQ5aBw8uGw4nlF1V40jnjaFgsaZgaIKUgzwcYxehruD9IrlqaSh8/oIjk7Fvo7Nzcf3ByqOYvSoVkoeY4WaE6BvsceGAtOPmdGEVTHLUNYmN94tXdY54w9EjGHxtqySIT3EHsCO7zAWtF8gJwIOc8vzjtg81uc6nRRIqtOQIdPB3n18tdKVxHFNWfWY2chS78e0glFichVsiz3emCnm/q2tW+Icx4zgluyqThRJi1R87YoWfLc3yH0DsDYUlMbjrWIlB43YocUpwifYYbs6Irq/OrFc8vvrw14TIiWlrxGALmN7JFKzd4sqr8o3LPNmGVRu7m4L56DPdqZYQYWzcQiLW2GOTIMKR1F7xrc59wOD+qXZ41/M7i7Lxdtwu4R3XJNCJFZs9B9xs5KAvTM/N4lTW+jsNoSocyrsGgvDtcxfVDe5VfUawmKYNCG10PMDskMC2bleNG+28idyDMpKW9bX1gxZRfkjaae7BappqMnoKmSBRqdF3oTGqJrAUZ5AoC2BODflPQM/Pmkl88Qk4MMpnk4gmVYszZ8ESOT6aKtBTJGNYAtUAWfmmyZ5WRuabG6sEZGSPOosjPxEMIUhX5f6eFf+oI58I3GS6c5HcxWB6gdQykFlIicRnwcDecYtPEV4ON38Y+DJZfCFsFkT+dosOvoggorSQZPlRdinM/zQOt62kQ3HE3p24V8LTBVGKQBKGyLbLH3jYQd9k+7cMnJMCqdYoBkVH7eerj/MQgF/+ccL6OlctWvM=
  template:
    metadata:
      name: homeassistant-secrets
      namespace: homeassistant
