---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgAf29jX3Dxr2zZwrgjtXAoHU8sKdrGEtbXy+7td1ANY8/90qkGY5ZqdcUYuciTLhlnZG7xu3Go736BBGyMYMayMxvTIZseKMstN1ScwAZwVA+IoPklwvnSL76AxokauKv2rrAJRYxNH+62fFLhcwn4MBSJ8s+6xF3VLFJwX3llrRCRzaLGWzZlLqj7zx5XrtWMdEmtF9S4pCdGLS5VY5usinjpKjcGTczKYoFZbYQqIXGlFO6N4exlTIOHMVKvShzgj/dldASKeDzqHX7f09fSP+O3DWLSqmNIyDxTbQL/OxlcPJ5K3BqAWt7icfuBDly9g0eUi59CqBVJDa3xV0pHiA3sG+D0vaaRhTg4B6pzgjIobjhQZfOct+DPZyLO8NIVD4Rgo65YXSyI6+Wlc3+PxatYBbcdrLKOfi9jXlCuUJ5lUPg34UJ6ElK0+dLY9HtS28pRymA88DxXHmdYybbQcQhsZzjfMOOcz49Nx6IZ5e3lWjxxG9s8wli3MP/7eLjmFG/wrcYojWoOIuuwx83rfctM3Br4INURy8WPAoSl9KmU3LqcWeDM0LCO/o3zhyoJVpEWZM8Jsi4cbf95Ywa6sOtGj0i0D4XwTotBxkg/UJTPR1PV20Gk1a5tmNOhWoQoVO6yAeJJfjwJcJ0lXiYFYjLrQ1wZYIvf57Ml0bSrTU67JLYeCFTjz9KnC0eZ1IdHWqo10y/dV4dXTUZnwvu12LXboWhNkvtNSEVcMeMHhYuMiLzosXwxvdH1TrXKi2HZvTgL5kXQ/jq1eMhnKy/hN625Q+wfwXn5XUzPBol8XGmjSvorZtDFaPSmrE0l4hSuf1KWQ8D1n5yZbNf6/kgJlebMJPH3oM5ZEoQh4G6g2BoxCpG9yGFiGD9SojX/jtS9LD0Wr5Gn+A8nxy56nVwB9Z5h9sf7355fs6BjyIMOUJhm9ONmC
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
