---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgA9UrxAuibFl84l03CxxwNdIaCBYk0V5QyzMUJNwTAqS5RXwY74xUsWnJoAOJqnMkduq9oYzfO4vBRgi8iFbrPEGM/w/VIPpwkiprfL6G9cWEZF7GpdpUAcY0Vs6FeJOV6Dolxr27i9ujAcpxA9ktiwLEZoEQ9ph0E/+zDG81Ry0UTIif+/uiQSkz9LEH3PPtZvPm2i+QqsAlpgZl6wA9DVUxRRsNsc1L+3+5ZWRVQMjDcp1E31ccrrKL473CFPVuh6zRK+h9gVBs9EokuswZS1y3UYLe1gDbYTHNIVTTnl36Th3pWVyz7RF3orT4W5v0DlBG/GgZFHtk/W4H1/WCw89zndPMv3na+19e4plsH36wxzgpMjei025acH9ZywahRQc82Z6qdVJ0DYK5hOdLLqEcnG+gsLlsR9F9V4hUVdBkePQYhdFUxcorShzR5k2+YR3/Zrl1B8ys7IXPJ681/0Zaw/+Y/3xT8twh6l4TAFlQuoFcPUgoAzNXTLTC37MCi9ZKQ5uxQnZqfes1hEgvI53j0CLa90CnOXiEgVnsJRT16Rb5VxiGR5talRndWSJ636KR94c5PezNj0eFRytHDha8OJxcNBKSIINRJYy5U4SOf2rw34Ofu5KM/59drFEiIGYeWdvcuPtgE+gsT6j7DtkXfkuDLkyw1ilSAfAoKcORj3sh+EZdr47Er8pDrLpJ1gj6nLPDgD3HoKSMv7zmKfkOp+AG4beNnnK/4r5dMHDnBtfm/dx+irAa3FWaIhkJBCG8DUZv9XPKa12Zs11JuJH+VhrBCYo0fBrn3tuSqFGAghAMgqKAKv8tZJX3U2eZAkaJiFaZUYlEhyRHjDwRX/ItisQnqgsZq4MZZEy2PJGg4SYanObEsB0+B5zWWCFa0N34kUj4qyYy+p
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
