---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - csi-driver.yaml
  - controller.yaml
  - node.yaml
  - secret-rbac.yaml
  - storage-class.yaml
  - client-info-secret.yaml
